apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:rayaneadaoun/argocd_gke.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ....
    -----END OPENSSH PRIVATE KEY-----

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:rayaneadaoun/argocd_gke.git
      sshPrivateKeySecret:
        name: my-deploy-secret
        key: sshPrivateKey


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ressources
    repoURL: ssh://git@github.com/rayaneadaoun/argocd_gke.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true